CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(20) NOT NULL UNIQUE,
  password VARCHAR(20) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE discussion_zones (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE topics (
  id SERIAL PRIMARY KEY,
  discussion_zone_id INTEGER REFERENCES discussion_zones (id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users (id),
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE replies (
  id SERIAL PRIMARY KEY,
  topic_id INTEGER REFERENCES topics (id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users (id),
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);